name: ADR proposed
description: |
  When an issue is created as an architectural decision record, add a comment to
  describe how to automatically create the ADR documentation when the issue is
  closed as accepted. This action should only be used in conjunction with the
  ADR acceptance action or else the comment won't make any sense.

inputs:
  label:
    description: |
      The name of the issue label that indicates this issue is an ADR. Defaults
      to "ADR". This value is case sensitive!
    default: "ADR: accepted"
  repo-token:
    description: |
      A GitHub token with permission to write issue comments on your repository.
    required: true

runs:
  using: composite

  steps:
    - name: check for tags
      if: "${{github.event.issue.state != 'open' || !contains(github.event.issue.labels.*.name, inputs.label) }}"
      run: exit 0

    - name: add comment if appropriate
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.repo-token }}
        script: |
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });

          const botHasCommented = comments.some(({ user: { login }}) => login === 'github-actions[bot]');

          if(!botHasCommented) {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This issue appears to be a draft or in-progress ADR. When it is completed and accepted, add the ADR acceptance label and close the issue. This will start a process to create the ADR document and add it to the repo automatically. If you close the issue before adding the label, simply re-open and re-close it.'
            });
          }
