name: On release
on:
  release:
    types: [released]

jobs:
  update-tags:
    name: update tags
    runs-on: ubuntu
    steps:
      - name: checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: update the major version tag
        run: |
          TAG=${{ github.event.release.tag_name }}
          MAJOR="$(echo $TAG | sed -r 's/\.[0-9]+\.[0-9]+$//')"
          git tag -f $MAJOR $TAG
          git push -f --tags